import React, { FormEvent, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter, Link, Navigate, Route, Routes, useLocation, useNavigate } from "react-router-dom";
import { QueryClient, QueryClientProvider, useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import "./style.css";

type ApiError = Error & { status?: number };
async function api<T>(path: string, options: RequestInit = {}): Promise<T> {
  const response = await fetch(path, { credentials: "include", headers: { "Content-Type": "application/json", ...(options.headers || {}) }, ...options });
  if (!response.ok) { const body = await response.json().catch(() => ({})); const error: ApiError = Object.assign(new Error(body.message || body.error || "请求失败"), { status: response.status }); throw error; }
  return response.status === 204 ? ({} as T) : response.json();
}

function AuthPage({ register = false }: { register?: boolean }) {
  const navigate = useNavigate(); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const data = Object.fromEntries(new FormData(event.currentTarget)); try { await api(register ? "/v1/auth/register" : "/v1/auth/login", { method: "POST", body: JSON.stringify(data) }); navigate("/"); } catch (e) { setError((e as Error).message); } }
  return <main className="auth-shell"><div className="auth-card"><div className="brand"><span className="brand-mark">✦</span><span>AstraTrade <em>AI</em></span></div><p className="eyebrow">SIMULATION CONSOLE</p><h1>{register ? "加入 AstraTrade AI" : "欢迎回来"}</h1><p className="muted">{register ? "使用邀请码创建你的模拟交易账户" : "登录查看你的模拟 Agent"}</p><form onSubmit={submit} className="stack"><label>邮箱<input name="email" type="email" required placeholder="you@example.com" /></label><label>密码<input name="password" type="password" minLength={12} required placeholder="至少 12 位" /></label>{register && <label>邀请码<input name="invite_code" required placeholder="ASTRA-..." /></label>}{error && <div className="error">{error}</div>}<button className="primary" type="submit">{register ? "创建账户" : "登录控制台"}</button></form><p className="switch">{register ? "已有账户？" : "还没有账户？"}<Link to={register ? "/login" : "/register"}>{register ? "立即登录" : "使用邀请码注册"}</Link></p></div></main>;
}

function Layout({ children }: { children: React.ReactNode }) {
  const navigate = useNavigate(); const location = useLocation(); const me = useQuery({ queryKey: ["me"], queryFn: () => api<{ email: string; role: string }>("/v1/auth/me"), retry: false });
  useEffect(() => { if (me.error && (me.error as ApiError).status === 401) navigate("/login"); }, [me.error, navigate]);
  async function logout() { await api("/v1/auth/logout", { method: "POST" }); navigate("/login"); }
  if (me.isLoading) return <div className="loading">正在加载 AstraTrade AI…</div>;
  return <div className="app-shell"><aside><div className="brand"><span className="brand-mark">✦</span><span>AstraTrade <em>AI</em></span></div><div className="mode-pill">模拟交易 · BTC/USDT</div><nav>{[["/", "总览"],["/agent", "Agent 配置"],["/activity", "活动记录"],["/settings", "账户设置"]].map(([path, label]) => <Link className={location.pathname === path ? "active" : ""} to={path} key={path}>{label}</Link>)}{me.data?.role === "admin" && <Link className={location.pathname.startsWith("/admin") ? "active" : ""} to="/admin">管理后台</Link>}</nav><div className="sidebar-bottom"><div className="user-chip"><span>{me.data?.email?.slice(0, 1).toUpperCase()}</span><div><strong>{me.data?.email}</strong><small>测试用户</small></div></div><button className="link-button" onClick={logout}>退出登录</button></div></aside><main className="content"><header><div><p className="eyebrow">ASTRATRADE AI / {location.pathname === "/" ? "总览" : "控制台"}</p><h2>模拟交易控制台</h2></div><div className="status-dot"><i />系统运行正常</div></header>{children}</main></div>;
}

function Dashboard() { const query = useQuery({ queryKey: ["dashboard"], queryFn: () => api<any>("/v1/dashboard"), refetchInterval: 10000 }); const data = query.data; if (query.isLoading) return <div className="loading">读取模拟账户…</div>; if (query.error) return <div className="error">{(query.error as Error).message}</div>; return <><div className="notice"><span>◈</span><div><strong>当前为模拟交易模式</strong><p>不会使用真实资金，也不会向 OKX 提交真实订单。所有数据仅用于验证策略与风控流程。</p></div></div><div className="metric-grid"><Metric label="模拟净值" value={`${Number(data.equity_usdt).toFixed(2)} USDT`} hint={`盈亏 ${Number(data.pnl_usdt).toFixed(2)} USDT`} /><Metric label="可用余额" value={`${Number(data.cash_usdt).toFixed(2)} USDT`} hint="模拟账户" /><Metric label="BTC 持仓" value={Number(data.btc).toFixed(8)} hint={`参考价 ${Number(data.price).toLocaleString()} USDT`} /><Metric label="Agent 状态" value={data.agent.status === "running" ? "运行中" : "已停止"} hint={data.agent.next_run_at ? `下次执行 ${new Date(data.agent.next_run_at).toLocaleString()}` : "尚未启动"} /></div><section className="panel"><div className="panel-title"><div><p className="eyebrow">RECENT EXECUTIONS</p><h3>最近模拟成交</h3></div><Link to="/activity">查看全部 →</Link></div>{data.recent_orders.length ? <div className="table-wrap"><table><thead><tr><th>时间</th><th>交易对</th><th>方向</th><th>数量</th><th>成交价</th><th>状态</th></tr></thead><tbody>{data.recent_orders.map((o: any) => <tr key={o.order_id}><td>{new Date(o.created_at).toLocaleString()}</td><td>{o.instrument}</td><td className="buy">买入</td><td>{o.quantity}</td><td>{o.price}</td><td><span className="tag green">已成交</span></td></tr>)}</tbody></table></div> : <div className="empty">启动 Agent 后，模拟成交会显示在这里。</div>}</section></>; }
function Metric({ label, value, hint }: { label: string; value: string; hint: string }) { return <div className="metric"><span>{label}</span><strong>{value}</strong><small>{hint}</small></div>; }

function AgentPage() { const client = useQueryClient(); const q = useQuery({ queryKey: ["agent"], queryFn: () => api<any>("/v1/agent") }); const [budget, setBudget] = useState(100); const [frequency, setFrequency] = useState("daily"); useEffect(() => { if (q.data) { setBudget(Number(q.data.budget_usdt)); setFrequency(q.data.frequency); } }, [q.data]); const save = useMutation({ mutationFn: () => api("/v1/agent", { method: "PUT", body: JSON.stringify({ budget_usdt: budget, frequency }) }), onSuccess: () => client.invalidateQueries({ queryKey: ["agent"] }) }); const action = useMutation({ mutationFn: (name: string) => api(`/v1/agent/${name}`, { method: "POST" }), onSuccess: () => { client.invalidateQueries({ queryKey: ["agent"] }); client.invalidateQueries({ queryKey: ["dashboard"] }); } }); if (q.isLoading) return <div className="loading">读取 Agent 配置…</div>; const running = q.data.status === "running"; return <div className="two-col"><section className="panel form-panel"><p className="eyebrow">CONSERVATIVE DCA</p><h3>保守定投 Agent</h3><p className="muted">Agent 仅在模拟账户中按规则执行 BTC/USDT 现货定投。</p><label>单次预算（USDT）<input type="number" min="1" max="500" value={budget} onChange={e => setBudget(Number(e.target.value))} /><small>系统上限：500 USDT / 次</small></label><label>执行频率<select value={frequency} onChange={e => setFrequency(e.target.value)}><option value="daily">每日</option><option value="weekly">每周</option></select></label><div className="risk-box"><strong>风控保护已启用</strong><span>每笔订单上限、余额检查和重复执行保护由服务端强制执行。</span></div><div className="actions"><button className="primary" onClick={() => save.mutate()} disabled={save.isPending}>保存配置</button>{running ? <button className="danger" onClick={() => action.mutate("stop")}>停止 Agent</button> : <button className="secondary" onClick={() => action.mutate("start")}>启动并执行一次</button>}</div>{(save.error || action.error) && <div className="error">{((save.error || action.error) as Error).message}</div>}</section><section className="panel agent-state"><div className={`agent-orb ${running ? "running" : ""}`}><span>✦</span></div><p className="eyebrow">AGENT STATUS</p><h3>{running ? "Agent 正在运行" : "Agent 已停止"}</h3><p className="muted">{running ? `下一次执行：${q.data.next_run_at ? new Date(q.data.next_run_at).toLocaleString() : "计算中"}` : "启动后会立即运行一次模拟定投"}</p><div className="state-line"><span>模式</span><strong>模拟交易</strong></div><div className="state-line"><span>标的</span><strong>BTC/USDT 现货</strong></div><div className="state-line"><span>手续费</span><strong>0.1%</strong></div></section></div>; }

function Activity() { const orders = useQuery({ queryKey: ["orders"], queryFn: () => api<any>("/v1/orders") }); const audit = useQuery({ queryKey: ["audit"], queryFn: () => api<any>("/v1/audit") }); return <><section className="panel"><div className="panel-title"><div><p className="eyebrow">SIMULATED ORDERS</p><h3>模拟订单</h3></div></div>{orders.data?.items?.length ? <div className="table-wrap"><table><thead><tr><th>时间</th><th>订单</th><th>数量</th><th>价格</th><th>手续费</th><th>状态</th></tr></thead><tbody>{orders.data.items.map((o: any) => <tr key={o.order_id}><td>{new Date(o.created_at).toLocaleString()}</td><td>{o.instrument} · 买入</td><td>{o.quantity}</td><td>{o.price}</td><td>{o.fee_usdt}</td><td><span className="tag green">已成交</span></td></tr>)}</tbody></table></div> : <div className="empty">暂时没有模拟订单。</div>}</section><section className="panel"><div className="panel-title"><div><p className="eyebrow">AUDIT TRAIL</p><h3>审计记录</h3></div></div><div className="audit-list">{audit.data?.items?.map((e: any, i: number) => <div className="audit" key={i}><span className="audit-dot" /><div><strong>{e.event_type}</strong><small>{new Date(e.created_at).toLocaleString()}</small></div></div>)}</div></section></>; }

function Settings() { const q = useQuery({ queryKey: ["connection"], queryFn: () => api<any>("/v1/connection") }); const start = async () => { const r = await api<any>("/v1/oauth/start", { method: "POST", body: JSON.stringify({ redirect_uri: window.location.origin + "/oauth/callback", scopes: ["read", "trade"] }) }); window.location.href = r.authorization_url; }; return <section className="panel form-panel"><p className="eyebrow">ACCOUNT & CONNECTION</p><h3>账户设置</h3><div className="connection-card"><div><strong>OKX 测试连接</strong><p>当前仅用于验证 Builder OAuth 页面和回调流程，不读取真实资产。</p></div><span className={`tag ${q.data?.connected ? "green" : "yellow"}`}>{q.data?.connected ? "已连接" : "未连接"}</span></div><button className="secondary" onClick={start}>开始测试连接</button><p className="hint">正式 OKX 凭据获批后，管理员将通过服务器环境变量启用生产 provider。</p></section>; }
function OAuthCallback() { const navigate = useNavigate(); const [message, setMessage] = useState("正在完成测试连接…"); useEffect(() => { const query = window.location.search; api(`/v1/oauth/callback${query}`).then(() => { setMessage("测试连接完成"); setTimeout(() => navigate("/settings"), 700); }).catch((e) => setMessage((e as Error).message)); }, [navigate]); return <div className="loading">{message}</div>; }
function Admin() { const q = useQuery({ queryKey: ["invites"], queryFn: () => api<any>("/v1/admin/invites") }); const client = useQueryClient(); const create = useMutation({ mutationFn: () => api<any>("/v1/admin/invites", { method: "POST", body: JSON.stringify({ max_uses: 1 }) }), onSuccess: () => client.invalidateQueries({ queryKey: ["invites"] }) }); const deactivate = useMutation({ mutationFn: (id: string) => api(`/v1/admin/invites`, { method: "DELETE", body: JSON.stringify({ id }) }), onSuccess: () => client.invalidateQueries({ queryKey: ["invites"] }) }); return <section className="panel"><div className="panel-title"><div><p className="eyebrow">ACCESS CONTROL</p><h3>邀请码管理</h3></div><button className="primary" onClick={() => create.mutate()}>生成邀请码</button></div>{create.data?.code && <div className="invite-result">新邀请码：<strong>{create.data.code}</strong>（请安全复制，仅显示本次生成结果）</div>}<div className="table-wrap"><table><thead><tr><th>创建时间</th><th>使用次数</th><th>最大次数</th><th>状态</th><th>有效期</th><th></th></tr></thead><tbody>{q.data?.items?.map((i: any, n: number) => <tr key={n}><td>{new Date(i.created_at).toLocaleString()}</td><td>{i.uses}</td><td>{i.max_uses}</td><td><span className={`tag ${i.active ? "green" : "yellow"}`}>{i.active ? "有效" : "停用"}</span></td><td>{new Date(i.expires_at).toLocaleString()}</td><td>{i.active && <button className="link-button" onClick={() => deactivate.mutate(i.id)}>停用</button>}</td></tr>)}</tbody></table></div></section>; }

function Protected({ children }: { children: React.ReactNode }) { return <Layout>{children}</Layout>; }
function App() { return <Routes><Route path="/login" element={<AuthPage />} /><Route path="/register" element={<AuthPage register />} /><Route path="/oauth/callback" element={<Protected><OAuthCallback /></Protected>} /><Route path="/" element={<Protected><Dashboard /></Protected>} /><Route path="/agent" element={<Protected><AgentPage /></Protected>} /><Route path="/activity" element={<Protected><Activity /></Protected>} /><Route path="/settings" element={<Protected><Settings /></Protected>} /><Route path="/admin" element={<Protected><Admin /></Protected>} /><Route path="*" element={<Navigate to="/" replace />} /></Routes>; }
const client = new QueryClient(); createRoot(document.getElementById("root")!).render(<React.StrictMode><QueryClientProvider client={client}><BrowserRouter><App /></BrowserRouter></QueryClientProvider></React.StrictMode>);
